# Generated by Django 4.2.20 on 2025-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gameroom_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='has_answered',
            field=models.BooleanField(default=False),
        ),
    ]
